DSP-1245: Add more example metadata
dasch-swiss/dsp-ontologies pull request #13
Opened 2021-01-20 23:14 UTC by BalduinLandolt

DSP-1245

2021-01-21 12:16 UTC, mpro7 approved these changes
Thanks!

2021-01-21 12:16 UTC, mpro7 commented on example/example-metadata-maximal.ttl
> +        "totally not documented"^^xsd:string ;
Is this the example of string and URL type in the same property?

2021-01-21 16:05 UTC, mpro7 requested changes
Actually changing my mind ;)
all props are missing now `repository` part, so I'm getting `"http://ns.dasch.swiss/hasAbstract"` instead of `"http://ns.dasch.swiss/repository#hasAbstract"`

2021-01-22 08:59 UTC, mpro7 reviewed
Ok, IRI part was fixed, thanks!

2021-01-22 12:09 UTC, mpro7 commented
This is how `Place` object looks like in old example:
```
{
                        "@type": "https://schema.org/Place",
                        "https://schema.org/url": {
                            "@type": "https://schema.org/URL",
                            "https://schema.org/propertyID": {
                                "@type": "https://schema.org/PropertyValue",
                                "https://schema.org/propertyID": "Geonames"
                            },
                            "https://schema.org/url": "https://www.geonames.org/2017370/russian-federation.html"
                        }
                    }
```
and this is how it looks in minimal version:
```
{
            "@type": "https://schema.org/Place",
            "https://schema.org/url": {
                "@type": "https://schema.org/URL",
                "https://schema.org/propertyID": {
                    "@type": "https://schema.org/PropertyValue",
                    "https://schema.org/propertyID": "Geonames",
                    "https://schema.org/url": "https://www.geonames.org/2661604"
                }
            }
        }
```
The bottom url property is now inside `propertyID`. Which on is correct?

2021-01-25 08:27 UTC, BalduinLandolt commented
You're right, the old one is correct.

I'll fix it in the tool. Thanks for spotting!

2021-01-26 14:36 UTC, mpro7 commented
@BalduinLandolt could you please add multiple address please, it's `0-n` for `Person` and I didn't find it in both of examples.

2021-01-27 13:41 UTC, mpro7 commented
> @BalduinLandolt could you please add multiple address, it's `0-n` for `Person` and I didn't find it in both of examples.
> 
> EDIT:
> Not a case anymore. We agreed to make both properties equal = `0-1`

But maybe you can within this PR align above cardinalities.
Otherwise other things seems to be ok.

2021-02-03 11:20 UTC, mpro7 approved these changes

2021-02-03 11:23 UTC, merged